name: Deploy Development

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-dev --prefer-dist

      - name: Set permissions
        run: |
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache

  
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-dev --prefer-dist

      - name: Set permissions
        run: |
          sudo chmod -R 775 storage
          sudo chmod -R 775 bootstrap/cache
        #   sudo chmod -R o+rw storage
        #   sudo chmod 664 storage/logs/laravel.log
        #   sudo rm -rf /var/www/backend/

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./
          target: '/var/www/spelling-correction'
          strip-components: 1  # Adjust the value based on your project structur
          
    #   - name: Clean up
    #     run: sudo rm -rf vendor

    #   - name: Clear cache on server
    #     run: php artisan cache:clear
